# Generated by Django 4.2.4 on 2023-08-24 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paying',
            name='paid_for_curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.curs', verbose_name='оплата за курс'),
        ),
        migrations.AddField(
            model_name='paying',
            name='paid_for_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='university.lesson', verbose_name='оплата за урок'),
        ),
    ]
