# Generated by Django 4.2.3 on 2023-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paying',
            name='id_intent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id намерения платежа'),
        ),
        migrations.AddField(
            model_name='paying',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='статус платежа'),
        ),
        migrations.AlterField(
            model_name='paying',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('transfer', 'перевод на счет'), ('card', 'оплата картой')], default='transfer', max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
