# Generated by Django 4.2.3 on 2023-07-09 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0002_paying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paying',
            name='user',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
