# Generated by Django 4.2.3 on 2023-07-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribed',
        ),
    ]
