# Generated by Django 4.2.3 on 2023-08-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_delete_paying'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена урока, руб.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена урока, руб.'),
        ),
    ]
