# Generated by Django 4.2.3 on 2023-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_curs_amount_lesson_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена курса, руб.'),
        ),
    ]
